baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
# dir name of your blog content (default is `content/posts`)
contentTypeName = "post"

# ["orange", "blue", "red", "green", "pink"]
themeColor = "orange"

# if you set this to 0, only submenu trigger will be visible
showMenuItems = 4

# show selector to switch language
showLanguageSelector = false

# set theme to full screen width
fullWidthTheme = false

# center theme with default width
centerTheme = true

# set a custom favicon (default is a `themeColor` square)
# favicon = "favicon.ico"

# set all headings to their default size (depending on browser settings)
# it's set to `true` by default
oneHeadingSize = false

[params.twitter]
# set Twitter handles for Twitter cards
# see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
# do not include @
creator = "kidrigger"
site = ""

[languages]
[languages.en]
languageName = "English"
title = "Bob's Terminal"
subtitle = "Here's me nerding out."
owner = "Anish Bhobe"
keywords = ""
copyright = ""
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"

[languages.en.params.logo]
logoText = "Bob's Terminal"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "post"
name = "Posts"
url = "/post"
weight = "100"
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = "200"
[[languages.en.menu.main]]
identifier = "project"
name = "Projects"
url = "/project"
weight = "110"
[[languages.en.menu.main]]
identifier = "research"
name = "Research"
url = "/research"
weight = "110"

[markup.goldmark.renderer]
unsafe = true
